services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - db-data:/data
    environment:
      - DATABASE_URL=sqlite:////data/metallobox.db

volumes:
  db-data:
